api_key: "your-bunny-api-key-here"  # Replace with your Bunny.net API key

# IP Detection Settings
ip_detection:
  ipv4:
    enabled: true
  ipv6:
    enabled: true

# Logging Configuration
logging:
  enabled: true          # Set to false to disable all logging
  level: "INFO"         # DEBUG, INFO, WARNING, ERROR
  file: true            # Log to file (ddns.log)
  console: false        # Log to console (useful for debugging)

# Daemon Settings (for --daemon mode)
daemon:
  interval: 1800        # Check interval in seconds (1800 = 30 minutes)

# DNS Zones and Records
zones:
  - zone_id: "your-zone-id-1"  # Zone ID for example.com
    domain: "example.com"
    records:
      - subdomain: "home"
        types:
          - type: "A"
            ttl: 300
          - type: "AAAA"
            ttl: 300
      - subdomain: "adguard"
        types:
          - type: "AAAA"
            ttl: 300
      - subdomain: "media"
        types:
          - type: "A"
            ttl: 600
          - type: "AAAA"
            ttl: 600
      - subdomain: ""  # Root domain (example.com)
        types:
          - type: "A"
            ttl: 300
  - zone_id: "your-zone-id-2"  # Zone ID for mydomain.net
    domain: "mydomain.net"
    records:
      - subdomain: "www"
        types:
          - type: "A"
            ttl: 300
          - type: "AAAA"
            ttl: 300
      - subdomain: "mail"
        types:
          - type: "A"
            ttl: 600
          - type: "AAAA"
            ttl: 600
      - subdomain: "blog"
        types:
          - type: "AAAA"
            ttl: 300
  - zone_id: "your-zone-id-3"  # Zone ID for example.org
    domain: "example.org"
    records:
      - subdomain: ""  # Root domain (example.org)
        types:
          - type: "A"
            ttl: 300
          - type: "AAAA"
            ttl: 300
      - subdomain: "cloud"
        types:
          - type: "A"
            ttl: 300
      - subdomain: "mail"
        types:
          - type: "AAAA"
            ttl: 300
